// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bookmark: typeof import('./src/components/Bookmark.vue')['default']
    BookmarkList: typeof import('./src/components/BookmarkList.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SettingsButton: typeof import('./src/components/SettingsButton.vue')['default']
    SettingsSidebar: typeof import('./src/components/SettingsSidebar.vue')['default']
    ThemeToggler: typeof import('./src/components/ThemeToggler.vue')['default']
  }
}
